# Generated by Django 2.0.9 on 2018-11-18 03:11
from django.db import migrations


def add_transport_type_instances(apps, schema_editor):
    TransportType = apps.get_model('transports', 'TransportType')
    transport_types = (
        TransportType(name='bus', icon=''),
        TransportType(name='tram', icon=''),
        TransportType(name='bike', icon=''),
        TransportType(name='traficar', icon=''),
        TransportType(name='scooter', icon=''),
        TransportType(name='stop', icon=''),
    )
    TransportType.objects.bulk_create(transport_types)


class Migration(migrations.Migration):
    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_transport_type_instances,
            migrations.RunPython.noop,
        ),
    ]
