# Generated by Django 2.0.9 on 2018-11-18 04:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_auto_20181118_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportevent',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='transportevent',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
